version: "3.4"
services:
  atm:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
    command: sh ./startserver.sh
    ports:
      - 25565:25565
    volumes:
      - ./:/usr/src/app
